poses:
- name: home
  x: 0.6
  y: 0.0
  z: 0.8
  roll: 0.0
  pitch: 180.0
  yaw: 0.0
- name: pick_ready
  x: 0.5
  y: 0.2
  z: 0.6
  roll: 0.0
  pitch: 180.0
  yaw: 0.0
- name: scene
  x: 0.6
  y: 1.0
  z: 0.6
  roll: 0.0
  pitch: 180.0
  yaw: -90.0
- name: leftstul
  x: -0.05
  y: 1.0
  z: 0.1
  roll: 0.0
  pitch: 180.0
  yaw: 0.0
- name: bookright
  x: 0.9
  y: 1.15
  z: 0.42
  roll: 0.0
  pitch: 180.0
  yaw: 90.0
- name: bookleft
  x: 0.48
  y: 1.15
  z: 0.42
  roll: 0.0
  pitch: 180.0
  yaw: 90.0
